spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://3.91.199.152:8080/realms/Nseremwe
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 9001

jwt:
  auth:
    converter:
      resource-id: nseremwe-sms-api
      principle-attribute: preferred_username